// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nullinside.Api.Model;

#nullable disable

namespace Nullinside.Api.Model.Migrations
{
    [DbContext(typeof(NullinsideContext))]
    [Migration("20260505204105_AllowDisableOnHomepage")]
    partial class AllowDisableOnHomepage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.DockerDeployments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDockerComposeProject")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ServerDir")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("IsDockerComposeProject", "Name");

                    b.ToTable("DockerDeployments");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeatureToggle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Feature")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("FeatureToggle");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackComment");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackCommentReadReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FeedbackCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackCommentReadReceipt");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackReadReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackReadReceipt");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BannedUserTwitchId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TwitchBan");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TwitchId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TwitchUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("TwitchUser");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUserBannedOutsideOfBotLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitchId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TwitchUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TwitchUserBannedOutsideOfBotLogs");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUserChatLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitchId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TwitchUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TwitchUserChatLogs");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BanKnownBots")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TwitchUserConfig");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUserLive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("GoneLiveTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StreamTitle")
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TwitchUserLive");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitchId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TwitchLastScanned")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitchRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("TwitchToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TwitchTokenExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitchUsername")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedOn")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("RoleAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.Feedback", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackComment", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.Feedback", "Feedback")
                        .WithMany("Comments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nullinside.Api.Model.Ddl.User", "User")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackCommentReadReceipt", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.FeedbackComment", "FeedbackComment")
                        .WithMany("FeedbackCommentReadReceipts")
                        .HasForeignKey("FeedbackCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nullinside.Api.Model.Ddl.User", "User")
                        .WithMany("FeedbackCommentReadReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbackComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackReadReceipt", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.Feedback", "Feedback")
                        .WithMany("FeedbackReadReceipts")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nullinside.Api.Model.Ddl.User", "User")
                        .WithMany("FeedbackReadReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUserConfig", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.User", null)
                        .WithOne("TwitchConfig")
                        .HasForeignKey("Nullinside.Api.Model.Ddl.TwitchUserConfig", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.TwitchUserLive", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.User", "User")
                        .WithOne("TwitchUserLive")
                        .HasForeignKey("Nullinside.Api.Model.Ddl.TwitchUserLive", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.UserRole", b =>
                {
                    b.HasOne("Nullinside.Api.Model.Ddl.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.Feedback", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FeedbackReadReceipts");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.FeedbackComment", b =>
                {
                    b.Navigation("FeedbackCommentReadReceipts");
                });

            modelBuilder.Entity("Nullinside.Api.Model.Ddl.User", b =>
                {
                    b.Navigation("FeedbackCommentReadReceipts");

                    b.Navigation("FeedbackComments");

                    b.Navigation("FeedbackReadReceipts");

                    b.Navigation("Feedbacks");

                    b.Navigation("Roles");

                    b.Navigation("TwitchConfig");

                    b.Navigation("TwitchUserLive");
                });
#pragma warning restore 612, 618
        }
    }
}
